
"use client"

import { useEffect, useState } from "react"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { DatePicker } from "@/components/ui/date-picker"
import { useToast } from "@/hooks/use-toast"
import type { Tour } from "@/lib/types"

interface TripFormProps {
  isOpen: boolean
  onOpenChange: (isOpen: boolean) => void
  onSave: (tour: Tour) => void
  tour: Tour | null
}

export function TripForm({ isOpen, onOpenChange, onSave, tour }: TripFormProps) {
  const [destination, setDestination] = useState("")
  const [date, setDate] = useState<Date | undefined>()
  const [price, setPrice] = useState("")
  const [totalSeats, setTotalSeats] = useState("")
  const [busCount, setBusCount] = useState("")
  const { toast } = useToast()

  useEffect(() => {
    if (tour) {
      setDestination(tour.destination)
      setDate(tour.date)
      setPrice(String(tour.price))
      setTotalSeats(String(tour.totalSeats))
      setBusCount(String(tour.busCount))
    } else {
      // Reset form for new trip
      setDestination("")
      setDate(undefined)
      setPrice("")
      setTotalSeats("40")
      setBusCount("1")
    }
  }, [tour, isOpen])

  const handleSubmit = () => {
    if (!destination || !date || !price || parseFloat(price) <= 0) {
      toast({
        title: "Faltan datos",
        description: "Por favor, completa todos los campos obligatorios.",
        variant: "destructive"
      })
      return
    }

    onSave({
      id: tour?.id || "", // ID will be generated by the parent component for new trips
      destination,
      date,
      price: parseFloat(price),
      totalSeats: parseInt(totalSeats) || 40,
      busCount: parseInt(busCount) || 1,
    })
  }

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>{tour ? "Editar Viaje" : "Crear Nuevo Viaje"}</DialogTitle>
          <DialogDescription>
            {tour ? "Modifica los detalles del viaje." : "Completa los detalles para crear un nuevo viaje."}
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="destination">Destino</Label>
            <Input id="destination" value={destination} onChange={(e) => setDestination(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="date">Fecha</Label>
            <DatePicker date={date} setDate={setDate} className="h-10 w-full" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="price">Precio</Label>
            <Input id="price" type="number" value={price} onChange={(e) => setPrice(e.target.value)} placeholder="0"/>
          </div>
           <div className="space-y-2">
            <Label htmlFor="busCount">Micros</Label>
            <Input id="busCount" type="number" value={busCount} onChange={(e) => setBusCount(e.target.value)} placeholder="1"/>
          </div>
          <div className="space-y-2">
            <Label htmlFor="totalSeats">Asientos (por micro)</Label>
            <Input id="totalSeats" type="number" value={totalSeats} onChange={(e) => setTotalSeats(e.target.value)} placeholder="40"/>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button>
          <Button onClick={handleSubmit}>Guardar Cambios</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
